spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:mysql://127.0.0.1:3306/ersync?sslMode=DISABLED&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&allowPublicKeyRetrieval=true}
    username: ${LOCAL_DB_USERNAME:ersync_local}
    password: ${LOCAL_DB_PASSWORD:ersync_local_password}
