package com.hansungteam.ersync.audit.domain;

/** MVP에서 보존해야 하는 주요 감사 행위입니다. */
public enum AuditAction {
    INVITATION_ISSUED,
    INVITATION_USED,
    INVITATION_EXPIRED,
    INVITATION_REVOKED,
    HOSPITAL_RECEIVING_STATUS_CHANGED,
    CONTACT_SHARING_CONSENT_RECORDED,
    TRANSPORT_REQUEST_CREATED,
    HOSPITAL_SEARCH_STARTED,
    HOSPITAL_SEARCH_EXPANDED,
    HOSPITAL_OFFER_CREATED,
    HOSPITAL_OFFER_ACCEPTED,
    HOSPITAL_OFFER_REJECTED,
    HOSPITAL_OFFER_NO_RESPONSE,
    HOSPITAL_SEARCH_EXHAUSTED,
    HOSPITAL_SEARCH_RETRY_STARTED,
    DESTINATION_SELECTED,
    DESTINATION_CHANGED,
    HOSPITAL_ACCEPTANCE_WITHDRAWN,
    VITAL_SIGNS_ADDED,
    CONSCIOUSNESS_CHANGED,
    PRE_KTAS_CHANGED,
    TREATMENT_ADDED,
    AMBULANCE_LOCATION_UPDATED,
    TRANSPORT_CANCELLED,
    HANDOFF_REQUESTED,
    HANDOFF_CONFIRMED
}
